### ISSUE TITLE
wrong package json?

### ISSUE THREAD

**Issue by luismesas** [angelsanchez/nodejs-atdd-example#3]
There is a space on the coverage_unit script on "unit{SPACE}_mocha", is it ok?

**Comment by guumaster** [comment]
Yes, Mocha has two scripts, and istanbul uses _mocha,  the one that doesn't fork another process.

Chech here https://github.com/gotwarlost/istanbul/issues/44#issuecomment-16093330

**Comment by luismesas** [comment]
thanks!!
